# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boardUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 498)
        self.hole13 = QtWidgets.QLabel(Form)
        self.hole13.setGeometry(QtCore.QRect(140, 150, 371, 231))
        self.hole13.setText("")
        self.hole13.setPixmap(QtGui.QPixmap("board pic.jpg"))
        self.hole13.setObjectName("hole13")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 90, 91, 16))
        self.label_2.setObjectName("label_2")
        self.hole_4 = QtWidgets.QLabel(Form)
        self.hole_4.setGeometry(QtCore.QRect(310, 290, 47, 16))
        self.hole_4.setObjectName("hole_4")
        self.hole_5 = QtWidgets.QLabel(Form)
        self.hole_5.setGeometry(QtCore.QRect(350, 290, 47, 16))
        self.hole_5.setObjectName("hole_5")
        self.hole_6 = QtWidgets.QLabel(Form)
        self.hole_6.setGeometry(QtCore.QRect(390, 290, 47, 16))
        self.hole_6.setObjectName("hole_6")
        self.hole_7 = QtWidgets.QLabel(Form)
        self.hole_7.setGeometry(QtCore.QRect(420, 260, 47, 16))
        self.hole_7.setObjectName("hole_7")
        self.hole_8 = QtWidgets.QLabel(Form)
        self.hole_8.setGeometry(QtCore.QRect(390, 230, 47, 16))
        self.hole_8.setObjectName("hole_8")
        self.hole_9 = QtWidgets.QLabel(Form)
        self.hole_9.setGeometry(QtCore.QRect(350, 230, 47, 16))
        self.hole_9.setObjectName("hole_9")
        self.hole_10 = QtWidgets.QLabel(Form)
        self.hole_10.setGeometry(QtCore.QRect(320, 230, 47, 16))
        self.hole_10.setObjectName("hole_10")
        self.hole_1 = QtWidgets.QLabel(Form)
        self.hole_1.setGeometry(QtCore.QRect(200, 290, 47, 16))
        self.hole_1.setObjectName("hole_1")
        self.hole_2 = QtWidgets.QLabel(Form)
        self.hole_2.setGeometry(QtCore.QRect(240, 290, 47, 16))
        self.hole_2.setObjectName("hole_2")
        self.hole_3 = QtWidgets.QLabel(Form)
        self.hole_3.setGeometry(QtCore.QRect(280, 290, 47, 16))
        self.hole_3.setObjectName("hole_3")
        self.hole_11 = QtWidgets.QLabel(Form)
        self.hole_11.setGeometry(QtCore.QRect(270, 230, 47, 16))
        self.hole_11.setObjectName("hole_11")
        self.hole_12 = QtWidgets.QLabel(Form)
        self.hole_12.setGeometry(QtCore.QRect(230, 230, 47, 16))
        self.hole_12.setObjectName("hole_12")
        self.hole_13 = QtWidgets.QLabel(Form)
        self.hole_13.setGeometry(QtCore.QRect(200, 230, 47, 16))
        self.hole_13.setObjectName("hole_13")
        self.hole_0 = QtWidgets.QLabel(Form)
        self.hole_0.setGeometry(QtCore.QRect(160, 260, 47, 16))
        self.hole_0.setObjectName("hole_0")
        self.opponent_lbl = QtWidgets.QLabel(Form)
        self.opponent_lbl.setGeometry(QtCore.QRect(0, 10, 201, 20))
        self.opponent_lbl.setObjectName("opponent_lbl")
        self.turn_lbl = QtWidgets.QLabel(Form)
        self.turn_lbl.setGeometry(QtCore.QRect(370, 10, 201, 20))
        self.turn_lbl.setObjectName("turn_lbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Game ID : "))
        self.hole_4.setText(_translate("Form", "4"))
        self.hole_5.setText(_translate("Form", "4"))
        self.hole_6.setText(_translate("Form", "4"))
        self.hole_7.setText(_translate("Form", "0"))
        self.hole_8.setText(_translate("Form", "4"))
        self.hole_9.setText(_translate("Form", "4"))
        self.hole_10.setText(_translate("Form", "4"))
        self.hole_1.setText(_translate("Form", "4"))
        self.hole_2.setText(_translate("Form", "4"))
        self.hole_3.setText(_translate("Form", "4"))
        self.hole_11.setText(_translate("Form", "4"))
        self.hole_12.setText(_translate("Form", "4"))
        self.hole_13.setText(_translate("Form", "4"))
        self.hole_0.setText(_translate("Form", "0"))
        self.opponent_lbl.setText(_translate("Form", "Game Opponent : "))
        self.turn_lbl.setText(_translate("Form", "Your Turn:  "))

    def get_all_holes(self):
        # temp
        return [self.hole_0, self.hole_1, self.hole_2, self.hole_3, self.hole_4, self.hole_5, self.hole_6,
                self.hole_7, self.hole_8, self.hole_9, self.hole_10, self.hole_11, self.hole_12, self.hole_13]
